package org.openelisglobal.audittrail.access;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openelisglobal.common.action.IActionConstants;
import org.openelisglobal.common.log.LogEvent;
import org.openelisglobal.login.valueholder.UserSessionData;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.HandlerInterceptor;
import org.springframework.web.servlet.HandlerMapping;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * Records who viewed patient data. Changes are already recorded in
 * {@code history} by the auditable services; reads are not, so this interceptor
 * writes one {@code patient_access_log} row for each successful request to an
 * endpoint that returns patient-identifiable data: patient search, patient
 * details, results, validation, order views and patient reports.
 *
 * <p>
 * Off unless {@code org.openelisglobal.audit.read.enabled=true}. The endpoints
 * are {@link #DEFAULT_PATHS} unless {@code org.openelisglobal.audit.read.paths}
 * lists others (comma-separated Spring path patterns). Rows are written by
 * {@link PatientAccessLogWriter} off the request thread.
 */
@Component
public class PatientAccessAuditInterceptor implements HandlerInterceptor, WebMvcConfigurer {

    public static final List<String> DEFAULT_PATHS = List.of( //
            "/rest/patient-search-results", "/rest/patient-details", "/rest/patientByLabNumer",
            "/rest/patient-photos/**", "/rest/patient-id-documents/**", //
            "/rest/LogbookResults", "/rest/AccessionValidation", "/rest/SampleEdit", "/rest/order/search",
            "/rest/ElectronicOrders", "/rest/ReportPrint", //
            "/LogbookResults", "/PatientResults", "/AccessionResults", "/AccessionValidation", "/SampleEdit",
            "/ReportPrint");

    /** Request parameters and path variables that name a patient. */
    static final List<String> PATIENT_ID_NAMES = List.of("patientID", "patientId", "patientPK", "patientPk",
            "selPatient");

    /** Request parameters and path variables that name a lab (accession) number. */
    static final List<String> ACCESSION_NAMES = List.of("labNumber", "accessionNumber", "accessionDirect", "accession");

    private static final int MAX_QUERY_LENGTH = 2000;

    private final PatientAccessLogWriter writer;
    private final boolean enabled;
    private final List<String> paths;

    @Autowired
    public PatientAccessAuditInterceptor(PatientAccessLogWriter writer,
            @Value("${org.openelisglobal.audit.read.enabled:false}") boolean enabled,
            @Value("${org.openelisglobal.audit.read.paths:}") String paths) {
        this.writer = writer;
        this.enabled = enabled;
        this.paths = parsePaths(paths);
    }

    static List<String> parsePaths(String setting) {
        if (setting == null || setting.isBlank()) {
            return DEFAULT_PATHS;
        }
        return Arrays.stream(setting.split(",")).map(String::trim).filter(s -> !s.isEmpty()).toList();
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        if (enabled) {
            registry.addInterceptor(this).addPathPatterns(paths);
        }
    }

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler,
            Exception ex) {
        try {
            if (ex != null || response.getStatus() >= 400 || !isRead(request)) {
                return;
            }
            writer.submit(toRecord(request, response.getStatus()));
        } catch (RuntimeException e) {
            // never let auditing break the screen
            LogEvent.logError("Could not record patient access to " + request.getRequestURI(), e);
        }
    }

    /**
     * Reads are GETs. Patient reports are also generated by POST
     * ({@code /rest/ReportPrint}); other POSTs are changes, which history records.
     */
    static boolean isRead(HttpServletRequest request) {
        return "GET".equalsIgnoreCase(request.getMethod()) || request.getRequestURI().endsWith("/ReportPrint");
    }

    PatientAccessRecord toRecord(HttpServletRequest request, int status) {
        UserSessionData usd = userSessionData(request);
        Integer sysUserId = usd != null && usd.getSystemUserId() > 0 ? usd.getSystemUserId() : null;
        String loginName = usd != null ? usd.getLoginName() : authenticatedName();
        String query = request.getQueryString();
        if (query != null && query.length() > MAX_QUERY_LENGTH) {
            query = query.substring(0, MAX_QUERY_LENGTH);
        }
        return new PatientAccessRecord(new Timestamp(System.currentTimeMillis()), sysUserId, loginName,
                request.getMethod(), resource(request), query, patientId(request),
                truncate(firstValue(request, ACCESSION_NAMES), 60), clientAddress(request), status);
    }

    private static UserSessionData userSessionData(HttpServletRequest request) {
        Object usd = request.getAttribute(IActionConstants.USER_SESSION_DATA);
        if (usd == null) {
            HttpSession session = request.getSession(false);
            usd = session == null ? null : session.getAttribute(IActionConstants.USER_SESSION_DATA);
        }
        return usd instanceof UserSessionData ? (UserSessionData) usd : null;
    }

    private static String authenticatedName() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        return auth == null ? null : auth.getName();
    }

    /** The path inside the application, e.g. {@code /rest/patient-details}. */
    static String resource(HttpServletRequest request) {
        String uri = request.getRequestURI();
        String context = request.getContextPath();
        if (context != null && !context.isEmpty() && uri.startsWith(context)) {
            uri = uri.substring(context.length());
        }
        return truncate(uri, 255);
    }

    static Integer patientId(HttpServletRequest request) {
        String value = firstValue(request, PATIENT_ID_NAMES);
        if (value == null || !value.matches("\\d{1,9}")) {
            return null;
        }
        return Integer.valueOf(value);
    }

    /**
     * First non-blank value among the request parameters, then the path variables.
     */
    static String firstValue(HttpServletRequest request, List<String> names) {
        for (String name : names) {
            String value = request.getParameter(name);
            if (value != null && !value.isBlank()) {
                return value.trim();
            }
        }
        Object vars = request.getAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE);
        if (vars instanceof Map<?, ?> map) {
            for (String name : names) {
                Object value = map.get(name);
                if (value != null && !String.valueOf(value).isBlank()) {
                    return String.valueOf(value).trim();
                }
            }
        }
        return null;
    }

    /**
     * The browser's address. Behind the gateway the request comes from the proxy,
     * which appends the address it saw to {@code X-Forwarded-For}; the last entry
     * is that one (earlier entries are whatever the client sent, so can't be
     * trusted).
     */
    static String clientAddress(HttpServletRequest request) {
        String forwarded = request.getHeader("X-Forwarded-For");
        if (forwarded != null && !forwarded.isBlank()) {
            String[] hops = forwarded.split(",");
            return truncate(hops[hops.length - 1].trim(), 255);
        }
        return request.getRemoteAddr();
    }

    private static String truncate(String value, int max) {
        return value == null || value.length() <= max ? value : value.substring(0, max);
    }
}
